_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.18
            "5": 0.19.11
            "6": 4.43.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
